### ISSUE TITLE
Correct communication format

### ISSUE THREAD

**Issue by FrantaD** [Steve-Mcl/node-red-contrib-omron-fins#6]
Hi,

I am testing communication between PLC NX102-1100 and RPI with NodeRed.

**PLC NX102-1100:**
> IP: 192.168.250.10/24 (port 2)
> FINS node address: 10
> FINS/UDP port number: 9600
> Memory settings: DM enable
> Global Variable: TestFins - INT - %D0 - retain

**RPI NodeRed:**
> IP: 192.168.250.11/24
> Connection Node properties:
> ![image](https://user-images.githubusercontent.com/46539219/102469425-0aa54a80-4053-11eb-8b17-e428814451ef.png)

**Connect FINS:**
> This is how I set it according to the help and it doesn't work.
> ![image](https://user-images.githubusercontent.com/46539219/102472506-a08ea480-4056-11eb-829d-2f90011dcafb.png)
> ![image](https://user-images.githubusercontent.com/46539219/102472672-d03dac80-4056-11eb-8de8-d60159ebdf58.png)
> ![image](https://user-images.githubusercontent.com/46539219/102472582-b734fb80-4056-11eb-8f58-3a45121a4c59.png)

>And this is how it works, but only the connection. Disconnection does not work.
> ![image](https://user-images.githubusercontent.com/46539219/102473169-712c6780-4057-11eb-91ae-c22a75a0ae41.png)
> ![image](https://user-images.githubusercontent.com/46539219/102473077-4e9a4e80-4057-11eb-99f7-f3e0430e5cd9.png)

**Q:** How is it supposed to be right?

**Write data by FINS write:**
> ![image](https://user-images.githubusercontent.com/46539219/102473489-cc5e5a00-4057-11eb-9dfb-d2090825a161.png)
> ![image](https://user-images.githubusercontent.com/46539219/102473530-d8e2b280-4057-11eb-989d-75c3842ac173.png)
> ![image](https://user-images.githubusercontent.com/46539219/102473567-e304b100-4057-11eb-968b-7855a208d07c.png)

**Q:** What is the correct response format for one INT variable.

Thank you for your help
Frantisek

**Comment by Steve-Mcl** [comment]
**Hi, please tell me ...**
node-red version (visible on the node-red menu)
nodejs version (run `node -v`)


**This is how to read a value...**
![image](https://user-images.githubusercontent.com/44235289/102481593-d2553a80-4059-11eb-8916-96d7f121f211.png)

**Example...**

```
[{"id":"c27543e7.83a9c","type":"FINS Read","z":"a2a9b7f9.ae1948","name":"","connection":"dfa87a08.a088f8","addressType":"msg","address":"topic","countType":"num","count":1,"msgPropertyType":"msg","msgProperty":"payload","outputFormatType":"list","outputFormat":"unsignedkv","x":730,"y":40,"wires":[["6845a434.51820c"]]},{"id":"80f39ad6.addbf8","type":"inject","z":"a2a9b7f9.ae1948","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"D100","payload":"","payloadType":"str","x":560,"y":40,"wires":[["c27543e7.83a9c"]]},{"id":"6845a434.51820c","type":"debug","z":"a2a9b7f9.ae1948","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":910,"y":40,"wires":[]},{"id":"dfa87a08.a088f8","type":"FINS Connection","name":"My PLC","host":"192.168.0.1","port":"9600","MODE":"CSCJ","ICF":"128","DNA":"","DA1":"","DA2":"","SNA":"","SA1":"","SA2":""}]
```

**Comment by FrantaD** [comment]
node-red version: 1.2.6
nodejs version: 12.20.0

**About FINS Write:**
> Thank you for the example I have already discovered my mistake.

> ![image](https://user-images.githubusercontent.com/46539219/102483454-0d10a000-4065-11eb-8f15-1e09d5c4de50.png)

**For others, this is my working configuration:**
PLC:
> ![image](https://user-images.githubusercontent.com/46539219/102485799-629a7c00-4068-11eb-9eb6-b072abbe90de.png)
> ![image](https://user-images.githubusercontent.com/46539219/102485828-69c18a00-4068-11eb-9196-05023e7ed468.png)
> ![image](https://user-images.githubusercontent.com/46539219/102485841-6e863e00-4068-11eb-9359-0aaa043f21f7.png)
> ![image](https://user-images.githubusercontent.com/46539219/102485853-747c1f00-4068-11eb-99e1-eb37035cc280.png)

NodeRed:
![image](https://user-images.githubusercontent.com/46539219/102485949-99709200-4068-11eb-963d-0cce59511b66.png)
![image](https://user-images.githubusercontent.com/46539219/102485984-a9887180-4068-11eb-8f41-9e4e89ce294e.png)
`[
    {
        "id": "76a42c51.9d5c34",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "c27543e7.83a9c",
        "type": "FINS Read",
        "z": "76a42c51.9d5c34",
        "name": "",
        "connection": "1f37dade.2df355",
        "addressType": "msg",
        "address": "topic",
        "countType": "num",
        "count": 1,
        "msgPropertyType": "msg",
        "msgProperty": "payload",
        "outputFormatType": "list",
        "outputFormat": "unsignedkv",
        "x": 330,
        "y": 160,
        "wires": [
            [
                "6845a434.51820c"
            ]
        ]
    },
    {
        "id": "80f39ad6.addbf8",
        "type": "inject",
        "z": "76a42c51.9d5c34",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "D0",
        "payload": "",
        "payloadType": "str",
        "x": 150,
        "y": 160,
        "wires": [
            [
                "c27543e7.83a9c"
            ]
        ]
    },
    {
        "id": "6845a434.51820c",
        "type": "debug",
        "z": "76a42c51.9d5c34",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 550,
        "y": 160,
        "wires": []
    },
    {
        "id": "d5beeae8.a7efe8",
        "type": "FINS Write",
        "z": "76a42c51.9d5c34",
        "name": "",
        "connection": "1f37dade.2df355",
        "addressType": "msg",
        "address": "topic",
        "dataType": "msg",
        "data": "payload",
        "msgPropertyType": "msg",
        "msgProperty": "payload",
        "x": 330,
        "y": 240,
        "wires": [
            [
                "6845a434.51820c"
            ]
        ]
    },
    {
        "id": "66d78d52.2ef9d4",
        "type": "inject",
        "z": "76a42c51.9d5c34",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "D0",
        "payload": "77",
        "payloadType": "str",
        "x": 150,
        "y": 240,
        "wires": [
            [
                "d5beeae8.a7efe8"
            ]
        ]
    },
    {
        "id": "1f37dade.2df355",
        "type": "FINS Connection",
        "name": "NX102",
        "host": "192.168.250.10",
        "port": "9600",
        "MODE": "NJNX",
        "ICF": "0x80",
        "DNA": "0",
        "DA1": "10",
        "DA2": "0",
        "SNA": "0",
        "SA1": "11",
        "SA2": "0"
    }
]`

**Comment by Steve-Mcl** [comment]
> Thank you for the example I have already discovered my mistake

So this is now resolved? Can we close this?

--- 

#### Notes (for anyone else reading)...

Explanation of the the problem @FrantaD  shows... 
![image](https://user-images.githubusercontent.com/44235289/102491164-b9ec1c80-4067-11eb-9303-f160b16d0e3d.png)

when writing values, you should choose number type...
![image](https://user-images.githubusercontent.com/44235289/102491380-00da1200-4068-11eb-9182-e88e664c0703.png)

**Comment by FrantaD** [comment]
The **connect** and **disconnect** commands still don't work for me, but I don't seem to need them.

The problem was solved for me and it is possible to close it.

**Comment by Steve-Mcl** [comment]
Yes, that does appear to be an issue.

I will leave this open until I fix it (but as you say, it makes no difference - the node auto connects, you simply cannot issue a disconnect)

TBH, I think I copied that text in the help from my Mitsubishi node (MITSI comms (in my experience) have been terrible (especially TCP) and the disconnect/connect capabilities were important.  Omron connections seem to works for very long periods without issue)

**Comment by Steve-Mcl** [comment]
@FrantaD  fixed in new version 0.3.1

Thank you for taking the time to report the issue.
